import type { Monaco } from '@monaco-editor/react'

export const APP_MONACO_THEMES = [
	'hndb-github-light',
	'hndb-one-dark',
	'hndb-tokyo-night',
	'hndb-gruvbox-dark',
	'hndb-nord',
	'hndb-catppuccin-mocha',
] as const

export type AppMonacoTheme = (typeof APP_MONACO_THEMES)[number]

type MonacoThemeDefinition = Parameters<Monaco['editor']['defineTheme']>[1]

const themeDefinitions: Record<AppMonacoTheme, MonacoThemeDefinition> = {
	'hndb-github-light': {
		base: 'vs',
		inherit: true,
		rules: [
			{ token: 'comment', foreground: '6E7781', fontStyle: 'italic' },
			{ token: 'keyword', foreground: 'CF222E', fontStyle: 'bold' },
			{ token: 'operator', foreground: '24292F' },
			{ token: 'number', foreground: '0550AE' },
			{ token: 'string', foreground: '0A3069' },
			{ token: 'string.escape', foreground: '1A7F37' },
			{ token: 'identifier', foreground: '24292F' },
			{ token: 'type', foreground: '8250DF' },
			{ token: 'delimiter', foreground: '57606A' },
			{ token: 'predefined', foreground: '953800' },
		],
		colors: {
			'editor.background': '#FFFFFF',
			'editor.foreground': '#24292F',
			'editorLineNumber.foreground': '#9AA4B2',
			'editorLineNumber.activeForeground': '#57606A',
			'editorCursor.foreground': '#0969DA',
			'editor.selectionBackground': '#DDF4FF',
			'editor.inactiveSelectionBackground': '#EAEEF2',
			'editor.lineHighlightBackground': '#F6F8FA',
			'editorIndentGuide.background1': '#E5E7EB',
			'editorIndentGuide.activeBackground1': '#BFCCD9',
			'editorWhitespace.foreground': '#D8DEE4',
			'editorBracketMatch.background': '#E7F3FF',
			'editorBracketMatch.border': '#218BFF',
		},
	},
	'hndb-one-dark': {
		base: 'vs-dark',
		inherit: true,
		rules: [
			{ token: 'comment', foreground: '5C6370', fontStyle: 'italic' },
			{ token: 'keyword', foreground: 'C678DD', fontStyle: 'bold' },
			{ token: 'operator', foreground: 'ABB2BF' },
			{ token: 'number', foreground: 'D19A66' },
			{ token: 'string', foreground: '98C379' },
			{ token: 'identifier', foreground: 'E06C75' },
			{ token: 'type', foreground: 'E5C07B' },
			{ token: 'delimiter', foreground: '7F848E' },
			{ token: 'predefined', foreground: '61AFEF' },
		],
		colors: {
			'editor.background': '#282C34',
			'editor.foreground': '#ABB2BF',
			'editorLineNumber.foreground': '#636D83',
			'editorLineNumber.activeForeground': '#ABB2BF',
			'editorCursor.foreground': '#61AFEF',
			'editor.selectionBackground': '#3E4451',
			'editor.inactiveSelectionBackground': '#343B45',
			'editor.lineHighlightBackground': '#2C313A',
			'editorIndentGuide.background1': '#343B45',
			'editorIndentGuide.activeBackground1': '#4B5263',
			'editorWhitespace.foreground': '#3B4048',
			'editorBracketMatch.background': '#36404D',
			'editorBracketMatch.border': '#56B6C2',
		},
	},
	'hndb-tokyo-night': {
		base: 'vs-dark',
		inherit: true,
		rules: [
			{ token: 'comment', foreground: '565F89', fontStyle: 'italic' },
			{ token: 'keyword', foreground: 'BB9AF7', fontStyle: 'bold' },
			{ token: 'operator', foreground: 'C0CAF5' },
			{ token: 'number', foreground: 'FF9E64' },
			{ token: 'string', foreground: '9ECE6A' },
			{ token: 'identifier', foreground: 'F7768E' },
			{ token: 'type', foreground: '7AA2F7' },
			{ token: 'delimiter', foreground: 'A9B1D6' },
			{ token: 'predefined', foreground: '2AC3DE' },
		],
		colors: {
			'editor.background': '#1A1B26',
			'editor.foreground': '#C0CAF5',
			'editorLineNumber.foreground': '#414868',
			'editorLineNumber.activeForeground': '#7AA2F7',
			'editorCursor.foreground': '#7AA2F7',
			'editor.selectionBackground': '#283457',
			'editor.inactiveSelectionBackground': '#24283B',
			'editor.lineHighlightBackground': '#1F2335',
			'editorIndentGuide.background1': '#24283B',
			'editorIndentGuide.activeBackground1': '#3B4261',
			'editorWhitespace.foreground': '#292E42',
			'editorBracketMatch.background': '#283457',
			'editorBracketMatch.border': '#7AA2F7',
		},
	},
	'hndb-gruvbox-dark': {
		base: 'vs-dark',
		inherit: true,
		rules: [
			{ token: 'comment', foreground: '928374', fontStyle: 'italic' },
			{ token: 'keyword', foreground: 'FB4934', fontStyle: 'bold' },
			{ token: 'operator', foreground: 'EBDBB2' },
			{ token: 'number', foreground: 'D3869B' },
			{ token: 'string', foreground: 'B8BB26' },
			{ token: 'identifier', foreground: 'FABD2F' },
			{ token: 'type', foreground: '8EC07C' },
			{ token: 'delimiter', foreground: 'A89984' },
			{ token: 'predefined', foreground: 'FE8019' },
		],
		colors: {
			'editor.background': '#282828',
			'editor.foreground': '#EBDBB2',
			'editorLineNumber.foreground': '#7C6F64',
			'editorLineNumber.activeForeground': '#D5C4A1',
			'editorCursor.foreground': '#FE8019',
			'editor.selectionBackground': '#504945',
			'editor.inactiveSelectionBackground': '#3C3836',
			'editor.lineHighlightBackground': '#32302F',
			'editorIndentGuide.background1': '#3C3836',
			'editorIndentGuide.activeBackground1': '#665C54',
			'editorWhitespace.foreground': '#403C3A',
			'editorBracketMatch.background': '#504945',
			'editorBracketMatch.border': '#FABD2F',
		},
	},
	'hndb-nord': {
		base: 'vs-dark',
		inherit: true,
		rules: [
			{ token: 'comment', foreground: '616E88', fontStyle: 'italic' },
			{ token: 'keyword', foreground: '81A1C1', fontStyle: 'bold' },
			{ token: 'operator', foreground: 'D8DEE9' },
			{ token: 'number', foreground: 'B48EAD' },
			{ token: 'string', foreground: 'A3BE8C' },
			{ token: 'identifier', foreground: 'EBCB8B' },
			{ token: 'type', foreground: '88C0D0' },
			{ token: 'delimiter', foreground: 'BFC7D5' },
			{ token: 'predefined', foreground: 'BF616A' },
		],
		colors: {
			'editor.background': '#2E3440',
			'editor.foreground': '#D8DEE9',
			'editorLineNumber.foreground': '#616E88',
			'editorLineNumber.activeForeground': '#ECEFF4',
			'editorCursor.foreground': '#88C0D0',
			'editor.selectionBackground': '#434C5E',
			'editor.inactiveSelectionBackground': '#3B4252',
			'editor.lineHighlightBackground': '#343D4E',
			'editorIndentGuide.background1': '#3B4252',
			'editorIndentGuide.activeBackground1': '#4C566A',
			'editorWhitespace.foreground': '#434C5E',
			'editorBracketMatch.background': '#434C5E',
			'editorBracketMatch.border': '#81A1C1',
		},
	},
	'hndb-catppuccin-mocha': {
		base: 'vs-dark',
		inherit: true,
		rules: [
			{ token: 'comment', foreground: '6C7086', fontStyle: 'italic' },
			{ token: 'keyword', foreground: 'CBA6F7', fontStyle: 'bold' },
			{ token: 'operator', foreground: 'CDD6F4' },
			{ token: 'number', foreground: 'FAB387' },
			{ token: 'string', foreground: 'A6E3A1' },
			{ token: 'identifier', foreground: 'F38BA8' },
			{ token: 'type', foreground: '89B4FA' },
			{ token: 'delimiter', foreground: 'BAC2DE' },
			{ token: 'predefined', foreground: '94E2D5' },
		],
		colors: {
			'editor.background': '#1E1E2E',
			'editor.foreground': '#CDD6F4',
			'editorLineNumber.foreground': '#6C7086',
			'editorLineNumber.activeForeground': '#BAC2DE',
			'editorCursor.foreground': '#F5E0DC',
			'editor.selectionBackground': '#45475A',
			'editor.inactiveSelectionBackground': '#313244',
			'editor.lineHighlightBackground': '#26263A',
			'editorIndentGuide.background1': '#313244',
			'editorIndentGuide.activeBackground1': '#585B70',
			'editorWhitespace.foreground': '#313244',
			'editorBracketMatch.background': '#45475A',
			'editorBracketMatch.border': '#CBA6F7',
		},
	},
}

export const registerAppMonacoThemes = (monaco: Monaco) => {
	for (const themeName of APP_MONACO_THEMES) {
		monaco.editor.defineTheme(themeName, themeDefinitions[themeName])
	}
}
