import Editor from '@monaco-editor/react'
import clsx from 'clsx'
import { AlertCircle, Check, LockIcon } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'

import { Button } from '@/components/ui/button'
import { registerAppMonacoThemes } from '@/lib/monaco-theme'
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select'
import { IColumn } from '@/interfaces'
import { usePreferencesStore } from '@/stores'
import { getSafeDisplayValue, getTypeInfo } from '@/utils'

interface EditableCellProps {
	initialValue: unknown
	column: IColumn
	onSave: (colName: string, newValue: unknown) => void
	isChanged: boolean
	isNewRow: boolean
	isDeleted?: boolean
}

const stripDefaultCast = (value: string) => value.trim().replace(/::[\w\s."[\]]+$/g, '')

const resolveLiteralDefaultValue = (
	columnDefault: string,
	options: {
		isNumber: boolean
		isBoolean: boolean
	},
) => {
	const trimmed = columnDefault.trim()
	const normalized = stripDefaultCast(trimmed)
	const upper = normalized.toUpperCase()

	if (
		upper.includes('CURRENT_TIMESTAMP') ||
		upper.includes('CURRENT_DATE') ||
		upper.includes('CURRENT_TIME') ||
		upper.includes('LOCALTIME') ||
		upper.includes('LOCALTIMESTAMP') ||
		upper.includes('NOW()')
	) {
		return null
	}

	if (/^'.*'$/.test(normalized)) {
		return normalized.slice(1, -1).replace(/''/g, "'")
	}

	if (options.isBoolean && /^(TRUE|FALSE|1|0)$/i.test(normalized)) {
		return normalized === '1' || upper === 'TRUE' ? 1 : 0
	}

	if (options.isNumber && /^-?\d+(\.\d+)?$/.test(normalized)) {
		return Number(normalized)
	}

	return null
}

const EditableCell = ({
	initialValue,
	column,
	onSave,
	isChanged,
	isNewRow,
	isDeleted = false,
}: EditableCellProps) => {
	const { column_name, data_type, is_primary, is_nullable, column_default } =
		column

	const isLocked =
		isDeleted || (is_primary && (!isNewRow || column_default !== null))

	const safeInitialValue = getSafeDisplayValue(initialValue, data_type)
	const { color: typeColor } = getTypeInfo(data_type)

	const [isSpecialEditing, setIsSpecialEditing] = useState(false)
	const [localValue, setLocalValue] = useState(
		safeInitialValue === null ? '' : safeInitialValue,
	)
	const [jsonError, setJsonError] = useState<string | null>(null)
	const inputRef = useRef<HTMLTextAreaElement>(null)
	const hasAutoFilled = useRef(false)

	const typeLower = data_type.toLowerCase()
	const isBoolean =
		typeLower.includes('bool') ||
		typeLower.includes('bit') ||
		typeLower.includes('tinyint(1)')
	const isJson =
		typeLower.includes('json') ||
		safeInitialValue?.startsWith('{') ||
		safeInitialValue?.startsWith('[')
	const isEnum = typeLower.includes('enum')
	const isNumber =
		['int', 'float', 'double', 'decimal', 'numeric', 'real'].some((t) =>
			typeLower.includes(t),
		) && !isBoolean
	const isTemporal =
		typeLower.includes('date') ||
		typeLower.includes('time') ||
		typeLower.includes('year')
	const valueTone = clsx(
		'font-mono text-[13px] leading-6',
		!isChanged && !isDeleted && typeColor,
		isDeleted && 'text-red-600 dark:text-red-400 line-through',
		isChanged && !isDeleted && 'text-foreground',
	)

	const parsedEnums =
		isEnum ?
			typeLower
				.replace('enum(', '')
				.replace(')', '')
				.split("'")
				.join('')
				.split(',')
		:	[]
	const monacoTheme = usePreferencesStore((state) => state.monacoTheme)
	const autoGeneratedDefaultPlaceholder =
		isNewRow && initialValue === undefined && column_default !== null ?
			String(column_default).trim()
		:	null

	useEffect(() => {
		if (
			isNewRow &&
			initialValue === undefined &&
			column_default !== null &&
			!hasAutoFilled.current
		) {
			hasAutoFilled.current = true
			const finalDefault = resolveLiteralDefaultValue(
				String(column_default),
				{
					isNumber,
					isBoolean,
				},
			)

			if (finalDefault !== null) {
				onSave(column_name, finalDefault)
			}
		}
	}, [
		isNewRow,
		initialValue,
		column_default,
		column_name,
		isNumber,
		isBoolean,
		onSave,
	])

	useEffect(() => {
		setLocalValue(safeInitialValue === null ? '' : safeInitialValue)
	}, [safeInitialValue])

	useEffect(() => {
		if (isJson && isSpecialEditing) {
			try {
				if (localValue.trim() !== '') JSON.parse(localValue)
				setJsonError(null)
			} catch (e: any) {
				setJsonError(e.message)
			}
		}
	}, [localValue, isJson, isSpecialEditing])

	const handleFinalSave = (valToSave: string) => {
		if (isLocked) return

		const trimmed = valToSave.trim()
		let finalValue: any = trimmed === '' ? null : trimmed

		if (
			!is_nullable &&
			finalValue === null &&
			!isBoolean &&
			!isEnum &&
			!isJson
		) {
			finalValue = ''
		}

		if (
			String(finalValue) ===
			(safeInitialValue === null ? '' : safeInitialValue)
		)
			return
		onSave(column_name, finalValue)
	}

	const displayLocalStr = getSafeDisplayValue(localValue, data_type)
	const deletedTextStyle =
		isDeleted ? 'line-through text-red-600 dark:text-red-400' : ''

	return (
		<div
			className={clsx(
				'relative flex h-full min-h-[44px] w-full items-center transition-colors duration-150',
				isChanged && !isDeleted ?
					'bg-amber-100/80 dark:bg-amber-500/15'
				:	'bg-transparent',
				is_primary &&
					!isChanged &&
					!isDeleted &&
					'bg-primary/[0.035] dark:bg-primary/[0.08]',
				isDeleted && 'pointer-events-none',
			)}
			onDoubleClick={(e) => {
				e.stopPropagation()
				if (!isLocked && !isDeleted && isJson) setIsSpecialEditing(true)
			}}>
			{isBoolean || isEnum ?
				<Select
					disabled={isLocked}
					value={
						localValue === '' || localValue === null ?
							is_nullable ?
								'null-value'
							:	undefined
						:	String(localValue)
					}
					onValueChange={(v) => {
						const finalV =
							v === 'null-value' ? null
							: isBoolean ?
								v === 'true' ?
									1
								:	0
							:	v
						onSave(column_name, finalV)
					}}>
					<SelectTrigger
						className={clsx(
							'flex h-full min-h-[44px] w-full items-center justify-between rounded-none border-none bg-transparent px-3 py-2 shadow-none outline-none focus:ring-0 focus-visible:ring-0',
							isChanged && !isDeleted ?
								'text-foreground'
							:	'text-foreground',
							isDeleted && 'opacity-100 disabled:opacity-100',
						)}>
						<div
							className={clsx(
								'flex-1 truncate text-left',
								valueTone,
							)}>
							{displayLocalStr === null ?
								<span
									className={clsx(
										'italic',
										isChanged && !isDeleted ?
											'text-amber-800 dark:text-amber-200'
										:	'text-neutral-400',
									)}>
									[NULL]
								</span>
							: isBoolean ?
								<span
									className={clsx(
										'rounded px-2 py-0.5 text-[11px] font-semibold uppercase tracking-[0.08em]',
										isChanged && !isDeleted ?
											'bg-amber-500/15 text-foreground'
										:	'',
										(
											!isDeleted &&
												displayLocalStr === 'true'
										) ?
											'text-green-600 bg-green-500/10'
										:	'',
										(
											!isDeleted &&
												displayLocalStr === 'false'
										) ?
											'text-red-600 bg-red-500/10'
										:	'',
									)}>
									{displayLocalStr}
								</span>
							:	<span>{displayLocalStr}</span>}
						</div>
						<span className='hidden'>
							<SelectValue />
						</span>
						{isLocked && !isDeleted && (
						<LockIcon
							size={14}
							className={clsx(
								isChanged ? 'text-foreground' : 'text-primary',
								'opacity-40 ml-2 shrink-0',
							)}
						/>
						)}
					</SelectTrigger>

					<SelectContent
						position='popper'
						sideOffset={2}
						className='z-[10000] w-[var(--radix-select-trigger-width)] max-h-[300px]'>
						{is_nullable && (
							<SelectItem
								value='null-value'
								className='italic text-muted-foreground'>
								[NULL]
							</SelectItem>
						)}

						{(isBoolean ? ['true', 'false'] : parsedEnums).map(
							(opt: string) => (
								<SelectItem
									key={opt}
									value={opt}>
									{isBoolean ?
										<span
											className={clsx(
												'px-2 py-0.5 rounded font-medium uppercase tracking-wider',
												opt === 'true' ?
													'text-green-600 bg-green-500/10'
												:	'text-red-600 bg-red-500/10',
											)}>
											{opt}
										</span>
									:	opt}
								</SelectItem>
							),
						)}
					</SelectContent>
				</Select>
			: isJson || (isLocked && !isDeleted) ?
				<div
					className={clsx(
						'group flex w-full items-center justify-between gap-2 px-3 py-2',
						!isLocked && 'cursor-pointer',
					)}>
						<div
							className={clsx(
								'truncate font-mono text-[13px] leading-6',
								!isChanged && !isDeleted && typeColor,
								isChanged && !isDeleted && 'text-foreground',
								deletedTextStyle,
							)}>
						{safeInitialValue === null && autoGeneratedDefaultPlaceholder ?
							<span className='italic text-muted-foreground'>
								{autoGeneratedDefaultPlaceholder}
							</span>
						: safeInitialValue === null ?
							<span
								className={clsx(
									'italic',
									isChanged && !isDeleted ?
										'text-amber-800 dark:text-amber-200'
									:	'text-neutral-400',
								)}>
								[NULL]
							</span>
						:	<span
								className={clsx(
									'font-mono text-[13px] leading-6',
								)}>
								{safeInitialValue}
							</span>
						}
					</div>
					{isLocked && !isDeleted && (
						<LockIcon
							size={14}
							className={clsx(
								'ml-2 shrink-0 text-muted-foreground opacity-40 transition-opacity group-hover:opacity-100',
							)}
						/>
					)}
				</div>
			:	<textarea
					ref={inputRef}
					readOnly={isLocked}
					className={clsx(
						'w-full h-full min-h-[44px] resize-none overflow-hidden whitespace-nowrap border-none bg-transparent px-3 py-2 font-mono text-[13px] leading-6 outline-none transition-colors',
						isChanged && !isDeleted ?
							'placeholder:text-amber-700 dark:placeholder:text-amber-200'
						:	'',
						!isChanged && !isDeleted && typeColor,
						isChanged && !isDeleted && 'text-foreground',
						!isChanged && !isDeleted && isTemporal && 'tabular-nums',
						!isChanged && !isDeleted && isNumber && 'tabular-nums',
						'focus:bg-primary/[0.045] focus:ring-1 focus:ring-primary/20',
						deletedTextStyle,
						isDeleted && 'cursor-not-allowed',
					)}
					value={localValue}
					spellCheck={false}
					onChange={(e) => {
						const val = e.target.value
						if (isNumber) {
							if (val === '' || /^-?\d*\.?\d*$/.test(val))
								setLocalValue(val)
						} else {
							setLocalValue(val)
						}
					}}
					onBlur={() => handleFinalSave(localValue)}
					onKeyDown={(e) => {
						if (e.key === 'Enter') {
							e.preventDefault()
							inputRef.current?.blur()
						}
						if (e.key === 'Escape') {
							setLocalValue(
								safeInitialValue === null ? '' : (
									safeInitialValue
								),
							)
							inputRef.current?.blur()
						}
					}}
					rows={1}
				/>
			}

			{isSpecialEditing && isJson && !isDeleted && (
				<div
					className='fixed inset-0 z-[99999] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4'
					onClick={(e) => {
						e.stopPropagation()
						setIsSpecialEditing(false)
					}}>
					<div
						className='w-full max-w-2xl h-[500px] bg-white dark:bg-[#1e2333] border rounded-xl shadow-2xl flex flex-col overflow-hidden text-foreground'
						onClick={(e) => e.stopPropagation()}>
						<div className='flex items-center justify-between px-4 py-3 border-b bg-muted/30'>
							<span className='font-bold uppercase flex items-center gap-2'>
								{jsonError ?
									<AlertCircle
										size={16}
										className='text-red-500'
									/>
								:	<Check
										size={16}
										className='text-green-500'
									/>
								}
								JSON Editor: {column_name}
							</span>
							<div className='flex gap-2'>
								<Button
									size='sm'
									variant='ghost'
									onClick={() => setIsSpecialEditing(false)}>
									Cancel
								</Button>
								<Button
									size='sm'
									onClick={() => {
										try {
											onSave(
												column_name,
												JSON.parse(localValue),
											)
											setIsSpecialEditing(false)
										} catch (e) {}
									}}
									disabled={!!jsonError}>
									Apply
								</Button>
							</div>
						</div>
						<div className='flex-1'>
							<Editor
								height='100%'
								beforeMount={registerAppMonacoThemes}
								defaultLanguage='json'
								theme={monacoTheme}
								value={localValue}
								onChange={(v) => setLocalValue(v || '')}
								options={{
									minimap: { enabled: false },
									fontSize: 14,
									lineNumbers: 'off',
									automaticLayout: true,
									formatOnPaste: true,
									padding: { top: 12 },
								}}
							/>
						</div>
					</div>
				</div>
			)}
		</div>
	)
}

export default EditableCell
